backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Web Developer"
      name: "web-developer"
      file: "content/web-developer.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}
    - label: "Valomies"
      name: "valomies"
      file: "content/valomies.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}
    - label: "WordPress-kehittäjä"
      name: "wordpress-kehittaja"
      file: "content/wordpress-kehittaja.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}
    - label: "Miksaaja"
      name: "miksaaja"
      file: "content/miksaaja.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}
    - label: "Kanelin kasvattaja"
      name: "kanelin-kasvattaja"
      file: "content/kanelin-kasvattaja.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}
    - label: "Tietosuojaseloste"
      name: "tietosuojaseloste"
      file: "content/tietosuojaseloste.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}