backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /_next/static/images
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
collections:
  - label: "Pages"
    name: "pages"
    folder: "content"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Meta-title", name: "metatitle", widget: "string"}
      - { label: "Meta-description", name: "metadesc", widget: "text"}
      - { label: "Body", name: "body", widget: "markdown", buttons: [bold, italic, link, heading-two, heading-three, heading-four, quote, bulleted-list, numbered-list]}
  - label: 'Articles'
    name: 'article'
    folder: 'content/articles'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: "Meta-title", name: "metatitle", widget: "string"}
      - { label: "Meta-description", name: "metadesc", widget: "text"}
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', buttons: [bold, italic, link, heading-two, heading-three, heading-four, quote, bulleted-list, numbered-list], required: true }